## Q1

In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
arr=np.array([[10,20,30],[40,50,60]])
print("Element at [0,1]: ",arr[0,1])
print("Row 1: ",arr[1,:])
print("Column2: ",arr[:,2])

Array:
 [[1 2 3]
 [4 5 6]]
Element at [0,1]:  20
Row 1:  [40 50 60]
Column2:  [30 60]


## Q2

In [2]:
arr=np.array([1,2,3],dtype='int32')
print("Datatype: ",arr.dtype)
arr=arr.astype('float64')
print("Updated type: ",arr.dtype)

Datatype:  int32
Updated type:  float64


## Q3

In [3]:
arr=np.array([1,2,3,4])
print("max: ",arr.max())
print("min: ",arr.min())
print("sum: ",arr.sum())
print("product: ",arr.prod())
print("Broadcasted result: ",arr+5)

max:  4
min:  1
sum:  10
product:  24
Broadcasted result:  [6 7 8 9]


## Q4

In [4]:
one_array = np.ones((2,3))
zero_array = np.zeros((2,3))
empty_array = np.empty((2,3))
print("ones array: \n",one_array,"\nzeros array:\n",zero_array,"\nempty array:\n",empty_array)
arr=np.array([[1,2,3],[4,5,6]])
print("Shape of this array: ",arr.shape)
reshape=arr.reshape(3,2)
print("Reshaped array:\n",reshape)
arr1=np.array([1,2,3])
copy_arr1=arr1.copy()
view_arr1=arr1.view()
print("copy: ",copy_arr1)
print("view: ",view_arr1)
arr2=np.array([1,2])
arr3=np.array([3,4])
concatenated=np.concatenate((arr1,arr2))
print("concatenated array: ",concatenated)
arr4 = np.array([5,2,9,1])
print("Sorted array: ",np.sort(arr4))

ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]] 
zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]] 
empty array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Shape of this array:  (2, 3)
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
copy:  [1 2 3]
view:  [1 2 3]
concatenated array:  [1 2 3 1 2]
Sorted array:  [1 2 5 9]


## Q5

In [7]:
arr = np.array([1,2,3,4])
np.save("My_array",arr)
loaded_arr=np.load('My_array.npy')
print("Loaded array: ",loaded_arr)

Loaded array:  [1 2 3 4]


## Q6

In [10]:
import pandas as pd
data =[10,20,30]
labels=['a','b','c']
series = pd.Series(data,index =labels)
print("value at label 'b:",series['b'] )

value at label 'b: 20


## Q7

In [11]:
data ={
    'Name':['Alice','Bob','Charlie',],
    'Age':[25,30,35],
    'city':['Newyork','Sanfransisco','LosAngelis']
}

df= pd.DataFrame(data)
print("DataFrame")
print(df)
print("\nrow at index 1: ")
print(df.iloc[1])

DataFrame
      Name  Age          city
0    Alice   25       Newyork
1      Bob   30  Sanfransisco
2  Charlie   35    LosAngelis

row at index 1: 
Name             Bob
Age               30
city    Sanfransisco
Name: 1, dtype: object


## Q8

In [13]:
df_csv =pd.read_csv("sample.csv")
print("Dataframe from csv: ")
print(df_csv)
df_json=pd.read_json("sample.json")
print("data from json: ")
print(df_json)

Dataframe from csv: 
   id           name  age          city                email
0   1  Alice Johnson   25      New York    alice@example.com
1   2      Bob Smith   30   Los Angeles      bob@example.com
2   3  Charlie Brown   28       Chicago  charlie@example.com
3   4   Diana Prince   32       Houston    diana@example.com
4   5    Ethan Clark   27       Phoenix    ethan@example.com
5   6    Fiona Davis   35  Philadelphia    fiona@example.com
6   7  George Miller   29   San Antonio   george@example.com
7   8  Hannah Wilson   26     San Diego   hannah@example.com
8   9      Ian Moore   31        Dallas      ian@example.com
9  10   Julia Taylor   24      San Jose    julia@example.com
data from json: 
   id           name  age          city                email
0   1  Alice Johnson   25      New York    alice@example.com
1   2      Bob Smith   30   Los Angeles      bob@example.com
2   3  Charlie Brown   28       Chicago  charlie@example.com
3   4   Diana Prince   32       Houston    dian

## Q9

In [14]:
data = {
    'Math':[90,85,80,95],
    'Science':[88,82,85,90],
    'English':[78,75,80,85]
}
df =pd.DataFrame(data)
print("Data Frame: \n",df)
correlation = df.corr()
print("\nCorrelation Matrix: \n",correlation)

Data Frame: 
    Math  Science  English
0    90       88       78
1    85       82       75
2    80       85       80
3    95       90       85

Correlation Matrix: 
              Math   Science   English
Math     1.000000  0.774597  0.552866
Science  0.774597  1.000000  0.827040
English  0.552866  0.827040  1.000000
